version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: sis-database
    environment:
      POSTGRES_USER: sis
      POSTGRES_PASSWORD: sis
      POSTGRES_DB: sis
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
