spring:
  security:
    user:
      name: user
      password: 123456

  datasource:
    url: jdbc:postgresql://localhost:5432/sis
    username: sis
    password: sis
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: b2Vxd2hlxLFvd3FoxLFlb3F3aMSxb2RuY8SxZGZxZWpoxLFvcmZobmtsOTg0MzY0MTIzMjEzMjE0NTU2NDMyMTM4OWXEsWRqZTk4MmozxLFmZGVuOTgyMzlybmZrZXdsZHNpZA==
  expiration: 14400000  #4 Hours In Milliseconds

login:
  attempts:
    failed: 5